-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table linked_account (
  id                            bigint generated by default as identity not null,
  user_id                       bigint,
  provider_user_id              varchar(255),
  provider_key                  varchar(255),
  constraint pk_linked_account primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  email                         varchar(255),
  name                          varchar(255),
  active                        boolean default false not null,
  email_validated               boolean default false not null,
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_linked_account_user_id on linked_account (user_id);
alter table linked_account add constraint fk_linked_account_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table linked_account drop constraint if exists fk_linked_account_user_id;
drop index if exists ix_linked_account_user_id;

-- drop all
drop table if exists linked_account;

drop table if exists users;

